source "http://api.berkshelf.com"

cookbook 'td-agent', :git => 'https://github.com/treasure-data/chef-td-agent.git'
cookbook 'elasticsearch', :git => 'https://github.com/elasticsearch/cookbook-elasticsearch.git'
cookbook 'kibana', :git => 'https://github.com/realityforge/chef-kibana.git'
cookbook 'timezone-ii', :git => 'https://github.com/L2G/timezone-ii.git'
