platform :ios, '7.0'

target :CTFluentLoggerSample do
  pod 'CocoaAsyncSocket'
  pod 'MessagePack'
  pod 'GCNetworkReachability'
end

target :CTFluentLoggerSampleMac do
  platform :osx, '10.9'
  pod 'CocoaAsyncSocket'
  pod 'MessagePack'
end
